spring:
  application:
    name: sample-client
  cloud:
    config:
      discovery:
        enabled: true            # 默认false，设为true表示使用注册中心中的configserver配置而不自己配置configserver的uri
        serviceId: sample-config  # 指定config server在服务发现中的serviceId，默认为：configserver
      fail-fast: true
      profile: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://rdserver:8769/eureka/
server:
  port: 8783